# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a50488d4ef99a3be87ed2750eaa9d9a07adc42be2b4dfb7a48d2a3b7ccb53be68df15ffcf1697fb25a5bb7ae80969ed409920ca59a6763d746d5ba74980b1fd3

test:
  secret_key_base: ae07456ffb3116b561e952fcbad4a5ff1fe8769964c84953be7c263c746d796cd13a4e9bb58725d7861f753f5722215873d43751ec6cb0b044d303361302c954

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
